../src/verilog/unpack.v
../src/verilog/adder_pp.v
../src/verilog/adder.v
../src/verilog/align.v
../src/verilog/complemmet_c.v
../src/verilog/compress3_2.v
../src/verilog/compress4_2.v
../src/verilog/compress6_2.v
../src/verilog/compressor3_2_group.v
../src/verilog/my_multp.v
../src/verilog/exponentComparison.v
../src/verilog/SAD_6_v2.v
../src/verilog/LZC.v
../src/verilog/normalize.v
../src/verilog/SAD_6.v
../src/verilog/shifter.v
../src/verilog/fpfma_pipeline.v
../src/verilog/CLA_adder.v
../src/verilog/carry_select_adder.v
../src/testbench/t_fpfma_pipeline.v

